<?php

namespace AdminBundle\Repository;

/**
 * userAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
