<?php

namespace AnnonceBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	private $em;

	protected function __contruct(){
		$this->em = $this->getDoctrine()->getManager();
		return $this->createQueryBuilder("a")
			->where("a.taxi= :val")
			->setParameter("taxi", true)
			->getQuery()->getResult();
	}


	public function getMesAnnonces(){
		$now = new \DateTime();
		return $this->createQueryBuilder("a")
			->where("a.auteur= :user")
			->andWhere("a.expiredAt < :date")
			->setParameter("user", $this->getUser())
			->setParameter("date", $now)
			->getQuery()->getResult();
	}


	public function getMesAnnoncesAnciennes(){
		return $this->createQueryBuilder("a")
			->where("a.auteur= :user")
			->andWhere("a.expiredAt < :date")
			->setParameter("user", $this->getUser())
			->setParameter("date", "??")
			->getQuery()->getResult();
	}


	private function getAnnoncesTaxi(){
		$repository = $this->em->getRepository('AnnonceBundle:Taxi');

	}

	private function getAnnoncesVtc(){
		$repository = $this->em->getRepository('AnnonceBundle:vtc');
	}

	private function getAnnoncesCovoiturage(){
		$repository = $this->em->getRepository('AnnonceBundle:covoiturage');
	}

	private function getAnnoncesDemenagement(){
		$repository = $this->em->getRepository('AnnonceBundle:Demenagement');
	}
}
